name: Build
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review, labeled ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '16'
  JAVA_DISTRIBUTION: 'corretto'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Build
        run: |
          ./gradlew build --no-configuration-cache
